name: Docs

on:
  # should be on workflow_dispatch, but that will only trigger from main
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
    doc:
        name: "Documentation build"
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: ubuntu-latest
                      python-version: "3.7"
                      channel-priority: "strict"
                      envfile: ".github/environment-docs.yml"
        steps:
        - uses: actions/checkout@v2

        - name: Cache conda
          uses: actions/cache@v2
          env:
            # Increase this value to reset cache if etc/example-environment.yml has not changed
            CACHE_NUMBER: 1
          with:
            path: ~/conda_pkgs_dir
            key: ${{ runner.os }}-${{ matrix.python-version }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles( matrix.envfile ) }}

        - name: Install Conda environment
          uses: conda-incubator/setup-miniconda@v2
          with:
            auto-update-conda: false
            python-version: ${{ matrix.python-version }}
            add-pip-as-python-dependency: true
            auto-activate-base: false
            activate-environment: docs
            channel-priority: ${{ matrix.channel-priority }}
            environment-file: ${{ matrix.envfile }}
            use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

        - name: Conda info
          shell: bash -l {0}
          run: |
            conda info -a
            conda list

        - name: Install librosa
          shell: bash -l {0}
          run: python -m pip install --upgrade-strategy only-if-needed -e .[docs]

        - name: Build documentations
          shell: bash -l {0}
          run: sphinx-multiversion docs/ build/html
